{% set name = "descriptastorus" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/descriptastorus-{{ version }}.tar.gz
  sha256: 8ba08d4f6d98033176974016078218b31dad9670558cae2cfa1c330852379820

build:
  entry_points:
    - storus = descriptastorus.cli.storus:main
    - storus-validate = descriptastorus.cli.validate:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas-flavor
    - scipy
    - rdkit
    - tqdm

test:
  imports:
    - descriptastorus
  commands:
    - storus --help
    - storus-validate --help

about:
  home: https://github.com/bp-kelley/descriptastorus
  summary: Descriptor storage and molecular file indexing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
