{% set name = "descriptastorus" %}
{% set version = "2.7.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/descriptastorus-{{ version }}.tar.gz
  sha256: a48f8c980e7489541e4811f592d32333bed99584093bfdeaf04d418f1894869f

build:
  entry_points:
    - storus = descriptastorus.cli.storus:main
    - storus-validate = descriptastorus.cli.validate:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas-flavor
    - scipy
    - rdkit
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - descriptastorus
  commands:
    - storus --help
    - storus-validate --help

about:
  home: https://github.com/bp-kelley/descriptastorus
  summary: Descriptor storage and molecular file indexing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
